/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import javax.swing.JButton;
import javax.swing.JLabel;
import proyecto.pkgfinal.Usuario;
import sql.newpackage.Conexion;



public class FSecundario extends javax.swing.JFrame {

    private Usuario user;
    FRegistrarViaje NextFrame = new FRegistrarViaje();
    FBuscarViaje OtherFrame = new FBuscarViaje();
    
    public FSecundario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        BTON_Buscar = new javax.swing.JButton();
        BTON_Registrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        Nombre.setText("Nombre");

        jLabel2.setText("Apellido");

        Apellido.setText("Apellido");

        BTON_Buscar.setText("BUSCAR WHEELS");
        BTON_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_BuscarActionPerformed(evt);
            }
        });

        BTON_Registrar.setText("REGISTRAR WHEELS");
        BTON_Registrar.setEnabled(false);
        BTON_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_RegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        ID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(ID)))
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Apellido)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(BTON_Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTON_Registrar)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre)
                    .addComponent(jLabel2)
                    .addComponent(Apellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ID))
                .addGap(99, 99, 99)
                .addComponent(BTON_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTON_Registrar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTON_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_BuscarActionPerformed
   OtherFrame.setVisible(true);
   OtherFrame.setUser(user);
        
        
    }//GEN-LAST:event_BTON_BuscarActionPerformed

    private void BTON_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_RegistrarActionPerformed
    NextFrame.setUser(user);
    NextFrame.getNombre().setText(user.getNombre());
    NextFrame.getTelefono().setText(String.valueOf(user.getTelefono()));
    NextFrame.getCodigo().setText(String.valueOf(user.getID()));
    NextFrame.setVisible(true);
    
    }//GEN-LAST:event_BTON_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSecundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSecundario().setVisible(true);
            }
        });
    }

    public JLabel getApellido() {
        return Apellido;
    }

    public void setApellido(JLabel Apellido) {
        this.Apellido = Apellido;
    }

    public JLabel getID() {
        return ID;
    }

    public void setID(JLabel ID) {
        this.ID = ID;
    }

    public JLabel getNombre() {
        return Nombre;
    }

    public void setNombre(JLabel Nombre) {
        this.Nombre = Nombre;
    }

    public JButton getjButton2() {
        return BTON_Registrar;
    }

    public void setjButton2(JButton jButton2) {
        this.BTON_Registrar = jButton2;
    }

    public Usuario getUser() {
        return user;
    }

    public void setUser(Usuario user) {
        this.user = user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton BTON_Buscar;
    private javax.swing.JButton BTON_Registrar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
